### PR TITLE
correct alignment of cloud boxes

### PR DESCRIPTION
**Pull request by ATREAY**
## Description

This pull request effectively resolves the associated issue: https://github.com/kubefirst/docs/issues/543

### CODE REVIEW

**Comment by fharper** [comment]
Your commits needs to be signed: more information at https://github.com/kubefirst/docs/blob/main/CONTRIBUTING.md#commits

**Comment by ATREAY** [comment]
Hey @fharper, I've signed the commit. I kindly request your review, and please let me know if any modifications are required.

**Review by fharper — CHANGES_REQUESTED** [review]
Can you remove the change to package-lock.json. Will keep the requirements as they are since you didn't update any packages to newer versions.

**Comment by ATREAY** [comment]
I have excluded the package-lock.json file from the commits to avoid any confusion.

**Review by fharper — APPROVED** [review]

**Comment by fharper** [comment]
Thanks for the fix @ATREAY !

**Pull request merged**
