### PR TITLE
fix: Updating docs for mkcert

### PR DESCRIPTION
**Pull request by konstructcarrie**
## Description
Adding mkcert details to install instructions for all clouds and updating current 2.7 version with these changes
Added these details for Azure for vNext
Fixes instances of kubefirst for capitalization (other branding updates) 

## Related Issue(s)
None found

## How to test
Validate that content appears where expected before this step https://kubefirst.konstruct.io/docs/aws/quick-start/install/cli#create-your-new-kubefirst-cluster for each cloud

### CODE REVIEW

**Comment by fharper** [comment]
Since it's not in the commit message, for history, there is also a lot of correction of branding naming in this commit.

@konstructcarrie there is also the addition of Azure in 2.7, is it wanted also? Just want to be sure as this PR was just for `mkcert` from my understanding. If so you'll need to fix the 2.7 docs menu that point to Azure v.next, and it would be nice to also update this commit title to reflect all the changes once you squash this PR.

**Comment by konstructcarrie** [comment]
> Since it's not in the commit message, for history, there is also a lot of correction of branding naming in this commit.
> 
> @konstructcarrie there is also the addition of Azure in 2.7, is it wanted also? Just want to be sure as this PR was just for `mkcert` from my understanding. If so you'll need to fix the 2.7 docs menu that point to Azure v.next, and it would be nice to also update this commit title to reflect all the changes once you squash this PR.

I removed the Azure directory from the 2.7 version. I wasn't thinking about the fact that it was on hold until 2.8

**Review by fharper — DISMISSED** [review]

**Comment by fharper** [comment]
@konstructcarrie you also need to remove Azure references in the sidebar for 2.7

**Comment by konstructcarrie** [comment]
> @konstructcarrie you also need to remove Azure references in the sidebar for 2.7

Yeah I did that but there are also imports/references that I'm not sure how to remove that are killing the build.

@mrsimonemms 
If you're able to help me sort that out ☝️  I can remove the Azure bits from this PR and we can chat about how you want to go about publishing that (given that it's available and we have no specific ETA on a 2.8 release). Let's catch up tomorrow :D

**Comment by fharper** [comment]
I can give a look tomorrow to fix the build if Simon doesn't have time, let me know.

Even if we release 2.8 tomorrow, Azure is now available in 2.7, so the docs should be in 2.7 also @mrsimonemms :)

**Comment by mrsimonemms** [comment]
I've created a [PR](https://github.com/konstructio/kubefirst-docs/pull/836) to add the fix into this PR - please take a look and see if you're happy adding into this PR.

**Review by mrsimonemms — APPROVED** [review]
Approved.

It might be worth making a common component that contains all the "we use `mkcert`" paragraph so that we only have to actually write it once. We can do this afterwards though

**Pull request merged**
