### PR TITLE
fix: wording for the GitLab group prerequisite

### PR DESCRIPTION
**Pull request by fharper**
Also add information about the fact that the name can be whatever the user want to avoid confusion.

### CODE REVIEW

**Comment by bil9000** [comment]
Be as prescriptive as possible. 
"You will need to create a group in gitlab with developer permissions named 'your-gitlab-group'."
Including a link to the create group in gitlab:
https://gitlab.com/groups/new#create-group-pane

**Comment by fharper** [comment]
How do you create a GitLab group with developer permissions? I don't see anything about permissions in the interface when I create a group, or when managing it afterwards. I think it was a text issue when we merged docs a while ago, and since most of our users are on GitHub, nobody noticed before. If it's really this permission, just need to be sure to know how to do it as I want to be sure it's clear in the docs :)

**Comment by bil9000** [comment]
Screenshot 2024-10-21 at 3 05 24 PM

**Comment by fharper** [comment]
My understanding of this is that it's not permissions, but more like GitLab getting more information about who will use the group to either display a different interface or send marketing material. If I read the text right before, that's the impression I get but more than happy to be wrong. 

CleanShot 2024-10-21 at 15 09 31@2x

There is also nothing in their docs on that (the permissions for each group should be defined somewhere, especially with the `other` group permission). It also change nothing no matter the answer I use in terms of the group created based on my tests, but I'm not a GitLab expert.

I asked @muse-sisay to help me understand this more clearly since he has a GitLab expertise that I definitely don't have.

**Comment by bil9000** [comment]
I didn't write the original docs, I'm just trying to decode them. 

What did this mean?
``` 
Create a [GitLab group](https://docs.gitlab.com/ee/user/group/) developer permissions.
```

**Comment by fharper** [comment]
> I didn't write the original docs, I'm just trying to decode them.

I did but not this part 😅 I think it's a typo, or it was before we created ourselves the GitLab groups `admins` & `developers`.  @jarededwards or @johndietz can highlight us if needed.

> What did this mean?

The changes I made in this PR which result in `Create a [GitLab group](https://docs.gitlab.com/ee/user/group/) with the name you want.`, which is simply to create a GitLab group where kubefirst can create the repositories and the sub-groups.

@muse-sisay confirmed there is no permissions at the group level. It's when you add users that you define the permissions, which is out of scope for kubefirst docs as it's GitLab specific and not needed for kubefirst.

**Comment by fharper** [comment]
😅

**Review by jairoFernandez — APPROVED** [review]

**Comment by fharper** [comment]
push the wrong button, this PR isn't close until approved and merged, my bad 🤦‍♂️

**Comment by muse-sisay** [comment]
Hey @bil9000, 

The role option that you see when you create a group is for marketing purpose. Your user (the user who creates the group) is automatically granted an `owner role`.

> I didn't write the original docs, I'm just trying to decode them.
What did this mean?

If you are a member of group, you need to at-least have `developer` role (permission) to be able to create groups and repositories( have Kubefirst create on your behalf).

**Comment by bil9000** [comment]
Thank you for the clarification @muse-sisay ! You rule!

**Pull request merged**
