### PR TITLE
feat: update to use http-server instead of nginx

### PR DESCRIPTION
**Pull request by muse-sisay**
## Description
This PR switches nginx for [http-sever](https://github.com/patrickdappollonio/http-server). Great thanks to @patrickdappollonio for helping port to http-server.

## Related Issue(s)
N/A

## How to test
N/A

### CODE REVIEW

**Comment by muse-sisay** [comment]
Waiting on the following feature/issue to be closed before merging this one. : P
- https://github.com/patrickdappollonio/http-server/issues/122
- https://github.com/patrickdappollonio/http-server/issues/120

**Comment by fharper** [comment]
@muse-sisay why are we doing this move? I wasn't part of the discussion, but I was away so I assumed @konstructcarrie approved this change?

**Comment by konstructcarrie** [comment]
@fharper  Not something I specifically asked for, but John and I did a bunch of stuff yesterday perhaps he can explain @johndietz

**Comment by muse-sisay** [comment]
Apologies for lack of communication, this should have been a draft PR. We are proposing the moving to `http-server` 
- as the syntax is much simple as compared to nginx. ( It's similar to nef
- Regarding this ticket https://linear.app/konstruct/issue/KRA-13/docs-typesense-scrapper-issue

**Comment by muse-sisay** [comment]
quick update on `KRA-13`: with recent changes typesense is able to index `54917` items. For reference the collection name is `kubefirst-muse-http-server_1728292039`

**Comment by fharper** [comment]
So is the only thing left is waiting for the third-party project we are using to finish adding the features we need? Do we have an ETA?

**Comment by muse-sisay** [comment]
Hi @fharper,
Sorry I took a while to get back to this. I worked with @patrickdappollonio to make change we need. We are good to merge this branch.

**Comment by fharper** [comment]
I will review it today, thanks

**Comment by fharper** [comment]
If everything works well, we'll need to do the same with https://github.com/konstructio/colony-docs

**Review by fharper — APPROVED** [review]

**Pull request merged**
